---
- hosts: cluster
  tasks:
    - name: Run the equivalent of "apt-get update"
      apt:
        update_cache: yes
      become: true
      become_user: root

    - name: Install Java JDK
      apt:
        name: openjdk-8-jdk
      become: true
      become_user: root

    - name: Install Java JRE
      apt:
        name: openjdk-8-jre
      become: true
      become_user: root
