---
- hosts: localhost
  tasks:
    - name: Install homebrew
      shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null

    - name: update brew
      shell: brew update

    - name: install Grafana
      shell: brew install grafana
      
# Reference: https://grafana.com/docs/installation/mac/