---
- hosts: cluster
  tasks:
    - name: Create hadoop installation directory
      file:
        path: /opt/hadoop/
        state: directory
        mode: '0775'
      become: true
      become_user: root

    - name: Create HDFS path
      file:
        path: /opt/hadoop_tmp/
        state: directory
        mode: '0775'
      become: true
      become_user: root
