---
- hosts: slaves
  tasks:
    - name: Copy from Master ('/opt/hadoop/hadoop' files) to the slaves
      synchronize:
        src: /opt/hadoop/hadoop/
        dest: /opt/hadoop/hadoop/
        perms: yes
        rsync_opts:
           - "--include=what_needed"
           - "--exclude=**/**"
      delegate_to: master
#      become: true
#      become_user: root
