---

- hosts: master
  tasks:
    - name: Replace 'MQTT_Kafka_bridge/config/setup.ini' for the one corresponding to the scenario
      copy:
        src: "/Users/lcjr86/Dropbox/MSc - Liverpool/CKIT-702--Computing Advisor Class/Implementation/msc_uol_dissertation/Ansible/MQTT_Kafka_bridge/config/scenario_2_setup.ini"
        dest: "~/Repositories/msc_uol_dissertation/Python/MQTT_Kafka_bridge/config/setup.ini"
    
    - name: Run the MQTT_Kafka_Bridge code
      shell: nohup python3 main.py &
      args:
        chdir: ~/Repositories/msc_uol_dissertation/Python/MQTT_Kafka_bridge/src/
      ignore_errors: yes