---
- import_playbook: scenario_2__10_run_sensor_emulator.yaml
- import_playbook: scenario_2__20_create_kafka_topic.yaml
- import_playbook: scenario_2__30_run_mqtt_kafka_bridge.yaml
- import_playbook: scenario_2__40_clean_influxdb_edge_data.yaml
#- import_playbook: scenario_2__50_run_pyspark_script.yaml