---

- hosts: master
  tasks:
    - name: Create kafka topic 'sensor.1'
      shell: /opt/apache_kafka/kafka_2.12-2.3.0/bin/kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic sensor.1
      become: true
      become_user: root
      ignore_errors: yes