---

- hosts: localhost
  tasks:
    - name: Replace 'Sensor_Emulator/config/setup.ini' for the one corresponding to the scenario
      copy:
        src: "/Users/lcjr86/Dropbox/MSc - Liverpool/CKIT-702--Computing Advisor Class/Implementation/msc_uol_dissertation/Ansible/Sensor_Emulator/config/scenario_1_setup.ini"
        dest: "/Users/lcjr86/Dropbox/MSc - Liverpool/CKIT-702--Computing Advisor Class/Implementation/msc_uol_dissertation/Python/Sensor_Emulator/config/setup.ini"


    - name: Activate Python Virtual Environment & run python code
      command: chdir="/Users/lcjr86/Dropbox/MSc - Liverpool/CKIT-702--Computing Advisor Class/Implementation/msc_uol_dissertation/Python/Sensor_Emulator/" {{ item }}
      with_items:
        - source venv/bin/activate
        - /src/python main.py

    # - name: Activate Python Virtual Environment
    #   shell: source venv/bin/activate
    #   args:
    #     chdir: "/Users/lcjr86/Dropbox/MSc - Liverpool/CKIT-702--Computing Advisor Class/Implementation/msc_uol_dissertation/Python/Sensor_Emulator/"

    # - name: Run "Sensor_Emulator" main.py
    #   shell: python main.py &amp
    #   args:
    #     chdir: "/Users/lcjr86/Dropbox/MSc - Liverpool/CKIT-702--Computing Advisor Class/Implementation/msc_uol_dissertation/Python/Sensor_Emulator/src/"

#- hosts: master
