---
- hosts: cluster
  tasks:
    - name: Create Apache Hadoop installation directory / folder
      file:
        path: /opt/hadoop/
        state: directory
        mode: '0775'
      become: true
      become_user: root

    - name: Create HDFS directory / folder (for the 'namenode' and 'datanode')
      file:
        path: /opt/hadoop_tmp/
        state: directory
        mode: '0775'
      become: true
      become_user: root
