---
- hosts: cluster
  tasks:
    - name: Create Kafka-Prometheus installation directory / folder
      file:
        path: /opt/apache_kafka/prometheus
        state: directory
        mode: '0775'
      become: true
      become_user: root  

    - name: Download Prometheus JMX exporter
      get_url:
        url: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.3.0/jmx_prometheus_javaagent-0.3.0.jar
        dest: /opt/apache_kafka/prometheus/jmx_prometheus_javaagent-0.3.0.jar
        mode: '0775'
      become: true
      become_user: root

    - name: Download Prometheus JMX exporter - config file
      get_url:
        url: https://raw.githubusercontent.com/prometheus/jmx_exporter/master/example_configs/kafka-0-8-2.yml
        dest: /opt/apache_kafka/prometheus/kafka-0-8-2.yml
        mode: '0775'
      become: true
      become_user: root