---
- hosts: cluster
  tasks:
    - name: Setup the connectivity on the cluster - Update /etc/hosts file (cluster 'master' and 'slaves' IP and name)
      blockinfile:
        path: /etc/hosts
        block: |
          192.168.56.103     master
          192.168.56.202     slave01
          192.168.56.203     slave02
          192.168.56.103     rpi3
          192.168.56.202     rpi4
          192.168.56.203     rpi5         
      become: true
      become_user: root
