---
- hosts: master
  tasks:
    - name: Adjust the permission for the files and folders at '/opt/hadoop'
      file:
        dest: /opt/hadoop
        owner: root
        group: root
        mode: '0775'
        recurse: yes
      become: true
      become_user: root
