---
- hosts: localhost
  tasks:
    - name: config prometheus
      blockinfile:
        path: ~/.config/prometheus.yml
        block: |
          - job_name: 'cluster'
            # Override the global default and scrape targets from this job every 5 seconds.
            scrape_interval: 5s
            static_configs:
              - targets: ['192.168.56.103:9100', '192.168.56.202:9100', '192.168.56.203:9100', '192.168.56.204:9100']

          - job_name: 'kafka'
            scrape_interval: 1s
            static_configs:
              - targets: ['192.168.56.103:7071']