{
 "title": "RPi Cluster metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Spark - output", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of messages per sensor - UTC time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "sensorId" ], "type": "tag" }
     ],
     "measurement": "sensor_data",
     "query": "SELECT cumulative_sum(\"tic\") FROM \"sensor_data\" WHERE $timeFilter GROUP BY \"sensorId\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data Processed (last 1) - UTC time",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "sensor_data",
     "query": "SELECT \"value\" FROM \"sensor_data\"  GROUP BY sensorId ORDER BY DESC LIMIT 1\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Number of messages processed by (py)Spark",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"value\") as \"number_of_messages\" FROM \"sensor_data\" GROUP BY \"sensorId\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Kafka Broker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Messages requested to be processed (by topic)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic!=\"\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Number of Messages arriving per Minute (by Topic)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Num Messages / min" }
   ],
   "targets": [
    {
     "expr": "round(sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic!=\"\"}[1m]) * 60))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out (processed) Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "MQTT Broker (Mosquitto)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Number of messages per sensor - UTC time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "sensorId" ], "type": "tag" }
     ],
     "measurement": "sensor_data",
     "query": "SELECT cumulative_sum(\"tic\") FROM \"sensor_data\" WHERE $timeFilter GROUP BY \"sensorId\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data arrived per sensor (last 1) - UTC time",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "sensorId" ], "type": "tag" }
     ],
     "measurement": "sensor_data",
     "query": "SELECT \"value\" FROM \"sensor_data\" GROUP BY \"sensorId\" ORDER BY DESC LIMIT 1\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Number of messages published",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"value\") as \"number_of_messages\" FROM \"sensor_data\" GROUP BY \"sensorId\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Host cpu usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Host memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(node_memory_MemTotal_bytes{} - node_memory_MemFree_bytes{} - node_memory_Buffers_bytes{} - node_memory_Cached_bytes{}) / node_memory_MemTotal_bytes{} ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Host disk usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - 100 * ( sum by (instance) (node_filesystem_free_bytes{}) /sum  by (instance) (node_filesystem_size_bytes{}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Server Data",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "node_uname_info{job=\"cluster\"}"
    }
   ]
  },
  {
   "title": "Host Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,device) (rate(node_network_receive_bytes_total{device!~\"^(lo|docker|veth|flannel|virbr).*\"}[1m]))",
     "legendFormat": "-> {{ instance}} {{ device }}"
    }
   ]
  }
 ]
}