---
- hosts: master
  tasks:

    - name: Download spark-streaming-kafka-0-8-assembly_2.11-2.2.0.jar
      get_url:
        url: https://search.maven.org/remotecontent?filepath=org/apache/spark/spark-streaming-kafka-0-8-assembly_2.11/2.2.0/spark-streaming-kafka-0-8-assembly_2.11-2.2.0.jar
        dest: /opt/hadoop/spark/spark-streaming-kafka-0-8-assembly_2.11-2.2.0.jar
        mode: '0775'
      become: true
      become_user: root

    - name: Add package 'spark-streaming-kafka'
      shell: /opt/hadoop/spark/bin/spark-submit --jars /opt/hadoop/spark/spark-streaming-kafka-0-8-assembly_2.11-2.2.0.jar
      become: true
      become_user: root
