---

- hosts: master
  tasks:
    - name: Create kafka consumer 'sensor.1'
      #shell: nohup KAFKA_OPTS="-javaagent:/opt/apache_kafka/prometheus/jmx_prometheus_javaagent-0.3.0.jar=7072:/opt/apache_kafka/prometheus/kafka-0-8-2.yml" /opt/apache_kafka/kafka_2.12-2.3.0/bin/kafka-console-consumer.sh bootstrap-server 192.168.56.103:9092 --topic sensor.1 --from-beggining > /dev/null 2>&1
      shell: nohup /opt/apache_kafka/kafka_2.12-2.3.0/bin/kafka-console-consumer.sh bootstrap-server 192.168.56.103:9092 --topic sensor.1 --from-beggining > /dev/null 2>&1
      become: true
      become_user: root
      ignore_errors: yes