---
- hosts: master
  tasks:
    - name: Create Apache Bahir installation directory
      file:
        path: /opt/apache_bahir/
        state: directory
        mode: '0775'
      become: true
      become_user: root  

    - name: Download apache-bahir-2.3.3-src.tar.gz
      get_url:
        url: https://www.apache.org/dyn/closer.lua/bahir/bahir-spark/2.3.3/apache-bahir-2.3.3-src.tar.gz
        dest: /opt/apache_bahir/nifi-1.8.0-bin.tar.gz
        mode: '0775'
      become: true
      become_user: root

    - name: Unzip apache-bahir-2.3.3-src.tar.gz
      unarchive:
        src: /opt/apache_bahir/apache-bahir-2.3.3-src.tar.gz
        dest: /opt/apache_bahir/
        remote_src: yes
      become: true
      become_user: root