---

- hosts: localhost

  vars_files:
    - ./vars/parameters.yaml
    
  tasks:
    - name: SENSOR EMULATOR - Replace the 'setup.ini' for the one corresponding to the current 'test case scenario'
      copy:
        src: "{{ localhost_Sensor_Emulator_test_case_scenarios_config_files_path }}/scenario_01_s1_t5_setup.ini"
        dest: "{{ localhost_Sensor_Emulator_config_files_path }}/setup.ini"

    - name: SENSOR EMULATOR - Start the application
      shell: source "{{ localhost_Sensor_Emulator_path }}/venv/bin/activate" && cd "{{ localhost_Sensor_Emulator_path }}/src/"  && nohup python main.py &
      ignore_errors: yes