---

- hosts: localhost

  vars_files:
    - ./vars/parameters.yml

  tasks:
    - name: Activate Python Virtual Environment & run python Sensor Emulator code
      shell: source "{{ localhost_Clean_InfluxDB_path }}/venv/bin/activate" && cd '{{ localhost_Clean_InfluxDB_path }}/src/'  &&  python main.py
      ignore_errors: yes